### ISSUE TITLE
Trình độ như thế nào mới đủ để học nodejs

### ISSUE THREAD

**Issue by piaggiovs** [Vunb/hoidap-nodejs#1]
Chào anh, em học lập trình cũng được 2 tháng rồi,chủ yếu tự học trên mạng,em có mua khóa học trên trang codeschool và đã học hết các phần javascript cơ bản rồi,sau đó em có chuyển qua học khóa nodejs của anh để học về ngôn ngữ phía sever, em học nodejs vì qua tìm hiểu nó cũng dùng javascript để viết mã nên chắc sẽ tiện và nhanh hơn cho việc học. Nhưng đến lúc bắt đầu vào học nodejs em thấy không hiểu. Cho em hỏi là tại kiến thức javascript cơ bản là không đủ để học nodejs hay em cần phải học một ngôn ngữ phía máy chủ khác như php đã rồi mới nên chuyển sang học nodejs ?. Em chưa từng viết dự án thực tế nào, mới chỉ học viết code theo nhiệm vụ bằng cách học tương tác trên mấy trang như codecademy và codeschool. Giờ em bối rối quá không biết học cái gì tiếp để có thể làm ra một sản phẩm thực tế.

**Comment by vunb** [comment]
Hi chào em @piaggiovs 

Anh cũng đã phản hồi câu hỏi của em trong diễn đàn lớp học trên Edumall. Vì là em mới tiếp cận với lập trình nên chắc chắn có những bỡ ngỡ, ai cũng vậy thôi, anh cũng vậy. Con người ai cũng phải tập đi bước đi đầu tiên mà.

Cách tiếp cận nhanh nhất là cứ làm theo, `lặp lại` cho đến khi gặp vấn đề đó, cứ theo các bước lập trình đó là làm được. Sau đó mới tìm hiểu nguyên nhân sâu xa, cốt lõi của vấn đề và giải pháp thực hiện.

Vì NodeJS là code phía server, nên có thể nó đang nhập nhằng chút đối với em. Nhưng anh nghĩ khi làm nhiều, đọc nhiều tài liệu rồi sẽ vỡ dần ra. Cái quan trọng nhất là sự tự tin vào chính mình ! 💃 

Như bạn @DinhThienPhuc sinh viên Vật lý kỹ thuật đã chuyển sang lập trình nodejs và đang thực tập ở công ty anh. Bạn ấy tập trung và bắt đầu với các dự án nhỏ. Và bây giờ đang join vào các dự án thực tế ở công ty anh, xây dựng các ứng dụng cho lĩnh vực sức khỏe, y tế.

Nếu em ở Hà Nội thì có thể đến công ty anh thực tập, hoặc tham gia vào lớp thực tập thứ 7 hàng tuần mà anh trực tiếp tham gia hướng dẫn các bạn lập trình.

Em có câu hỏi gì, thắc mắc ngay khi học các video bài học thì cứ mạnh dạn đặt câu hỏi. Câu hỏi ngu ngốc cũng được! Đừng ngại nhé, như vậy em sẽ khá nhanh hơn mà không phải chuyển sang tìm học một ngôn ngữ khác.

**Comment by piaggiovs** [comment]
anh cho em hỏi nếu muốn đến công ty anh thức tập ( VNPT đúng không ạ ? ) thì cần làm gì ạ, em tốt nghiệp nghành tài chính nhưng một vài lý do nên được tiếp cận với lập trình, dần dần thấy có hứng thú nên tìm các khóa học online tự học .

**Comment by vunb** [comment]
Anh mới chuyển công việc từ Viễn thông ra làm về Y tế! Nếu em muốn thực tập có thể liên hệ với anh theo email này vunb@nodejs.vn Rất vui khi em tham gia thực tập cùng mọi người, hôm nay, bên anh vẫn training cho các bạn thực tập buổi **nodejs** đầu tiên. Trước đó là học về lập trình cơ bản HTML, CSS, JavaScript, AngularJS, ... giờ chuyển về phía back-end. 😄

**Comment by piaggiovs** [comment]
anh cho em xin lịch thực tập được không ạ, em đã gửi email cho anh theo email trên bằng mail pvtien.tuithich@gmail.com.
