### ISSUE TITLE
Client phải đợi nhau.

### ISSUE THREAD

**Issue by mdbrelo** [Vunb/hoidap-nodejs#2]
Em đã học xong khóa học nodejs của anh. Nhưng trong khóa học về phần đồng bộ và bất đồng bộ anh làm hơi ít em chưa hiểu hết được đặc tính này của node js.

Hiện tại em đang bị gặp vấn đề với node js. Em sử dụng thư viện chilkat để gửi request (hàm có hỗ trợ bất đồng bộ em đã đọc trong document của chilkat). 
Khi em triển khai code trên server thì gặp vấn đề về hàng đợi. Người dùng sau phải đợi cho người dùng trước đó xử lý xong thì mới được xử lý.

Và em gặp khá nhiều vấn đề khi triển khai trên server. Anh có thể làm một khóa học hay 1 bài viết về những gì cần thiết để triển khai node js trên server không ạ. Em cảm ơn

**Comment by vunb** [comment]
Chào @mdbrelo 

Cảm ơn em đã tham gia khóa học và góp ý cho anh. Đúng là khi triển khai nodejs sẽ gặp nhiều vấn đề từ khâu cấu hình ip cho đúng network interface, quản lý cấu hình, theo dõi giám sát tới phân tải cho ứng dụng. A sẽ xem xét và bổ sung vào khóa học sắp tới!

**Comment by mdbrelo** [comment]
Cảm ơn anh mong anh sớm ra khóa học mới.

Anh có thể cho em biết vấn đề của em nguyên nhân ở đâu không ạ. Trên máy test của em cũng bị như vậy chứ không riêng khi triển khai trên server anh ạ

**Comment by vunb** [comment]
@mdbrelo em có thể post 1 đoạn code xử lý lên ko?

> Trên máy test của em cũng bị như vậy chứ không riêng khi triển khai trên server anh ạ

Có thể do có cách code của mình rồi, nên nhớ code js xử lý tuần tự và chỉ có 1 luồng. Đã xử lý bất đồng bộ (async) thì code của mình cũng phải bất đồng bộ hết

**Comment by mdbrelo** [comment]
Như vậy là trong node js muốn nhiều người dùng có thể cùng lúc tương tác đến server của mình thì bắt buộc code mình phải không đồng bộ 100% phải không anh

**Comment by vunb** [comment]
Đúng rồi e! 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdbrelo** [comment]
Vâng cảm ơn anh rất nhiều ạ
